// Local Host
### Get all Users
GET http://localhost:8080/users
### Get by ID
GET http://localhost:8080/users/65c7e09027d03db81f2eeb2d
### Get by ID
GET http://localhost:8080/users/65c7e09027d03db81f2eeb2e
### Get by ID
GET http://localhost:8080/users/65c7e09027d03db81f2eeb2f
### Get by ID
GET http://localhost:8080/users/65c7e09027d03db81f2eeb30

### POST User (create) 
POST http://localhost:8080/users HTTP/1:1
content-type: application/json

{
    "firstName": "Jason",
    "lastName": "Drebber",
    "email": "jason.drebber@example.com",
    "username": "jasondrebber",
    "password": "jasondrebber789",
    "date_of_birth": "11/12/1993",
    "country": "USA"
}

### PUT User (update)
PUT http://localhost:8080/users/65d02000113f611a668b0458 HTTP/1:1
Content-Type: application/json

{
    "firstName": "Drebber",
    "lastName": "Jason",
    "email": "jason.drebber@example.com",
    "username": "jasondrebber",
    "password": "jasondrebber789",
    "date_of_birth": "11/12/1993",
    "country": "USA"
}

### DELETE User
DELETE http://localhost:8080/users/65d02000113f611a668b0458 HTTP/1:1


### Get all Products
GET http://localhost:8080/products
### Get by ID
GET http://localhost:8080/products/65d01c481de3ffa43d09f174
### Get by ID
GET http://localhost:8080/products/65d01c481de3ffa43d09f175
### Get by ID
GET http://localhost:8080/products/65d01c481de3ffa43d09f176
### Get by ID
GET http://localhost:8080/products/65d01c481de3ffa43d09f177

### POST Product (create) 
POST http://localhost:8080/products HTTP/1:1
content-type: application/json

{
  "name": "Power Rangers: Red Ranger Action Figure",
  "price": "14.99",
  "category": "Action Figure"
}

### PUT Product (update)
PUT http://localhost:8080/products/65d02074113f611a668b0459 HTTP/1:1
Content-Type: application/json

{
  "name": "Power Rangers: Blue Ranger Action Figure",
  "price": "14.99",
  "category": "Action Figure"
}

### DELETE Product
DELETE http://localhost:8080/products/65d02074113f611a668b0459 HTTP/1:1


// Render
### Get all User
GET https://cse341-project2-jkeq.onrender.com/users
### Get by ID
GET https://cse341-project2-jkeq.onrender.com/users/65c7e09027d03db81f2eeb2d
### Get by ID
GET https://cse341-project2-jkeq.onrender.com/users/65c7e09027d03db81f2eeb2e
### Get by ID
GET https://cse341-project2-jkeq.onrender.com/users/65c7e09027d03db81f2eeb2f
### Get by ID
GET https://cse341-project2-jkeq.onrender.com/users/65c7e09027d03db81f2eeb30

### POST User
POST https://cse341-project2-jkeq.onrender.com/users HTTP/1:1
content-type: application/json

{
    "firstName": "Jason",
    "lastName": "Drebber",
    "email": "jason.drebber@example.com",
    "username": "jasondrebber",
    "password": "jasondrebber789",
    "date_of_birth": "11/12/1993",
    "country": "USA"
}

### PUT User (update)
PUT https://cse341-project2-jkeq.onrender.com/users/65d020ca87752020144b34f7 HTTP/1:1
Content-Type: application/json

{
    "firstName": "Drebber",
    "lastName": "Jason",
    "email": "jason.drebber@example.com",
    "username": "jasondrebber",
    "password": "jasondrebber789",
    "date_of_birth": "11/12/1993",
    "country": "USA"
}

### Delete User
DELETE https://cse341-project2-jkeq.onrender.com/users/65d020ca87752020144b34f7 HTTP/1:1


### Get all Products
GET https://cse341-project2-jkeq.onrender.com/products
### Get by ID
GET https://cse341-project2-jkeq.onrender.com/products/65d01c481de3ffa43d09f174
### Get by ID
GET https://cse341-project2-jkeq.onrender.com/products/65d01c481de3ffa43d09f175
### Get by ID
GET https://cse341-project2-jkeq.onrender.com/products/65d01c481de3ffa43d09f176
### Get by ID
GET https://cse341-project2-jkeq.onrender.com/products/65d01c481de3ffa43d09f177

### POST Product
POST https://cse341-project2-jkeq.onrender.com/products HTTP/1:1
content-type: application/json

{
  "name": "Power Rangers: Red Ranger Action Figure",
  "price": "14.99",
  "category": "Action Figure"
}

### PUT Product (update)
PUT https://cse341-project2-jkeq.onrender.com/products/65d0212f87752020144b34f8 HTTP/1:1
Content-Type: application/json

{
  "name": "Power Rangers: Blue Ranger Action Figure",
  "price": "14.99",
  "category": "Action Figure"
}

### Delete Product
DELETE https://cse341-project2-jkeq.onrender.com/products/65d0212f87752020144b34f8 HTTP/1:1